### ISSUE TITLE
Provide an interface for handling new deployments

### ISSUE THREAD

**Issue by michaelwheeler** [academic-innovation/django-lti#26]
This library should allow applications to specify custom behavior for handling and activating new deployments.

**Comment by cmurtaugh** [comment]
It would be nice to have the option to automatically register new deployment IDs. In many cases we want to be able to install the tool in multiple courses or sub-accounts without having to coordinate each install with the tool provider.

**Comment by michaelwheeler** [comment]
Yep, @cmurtaugh, I think that is a pretty common use case that isn't well supported by this library right now. Are you using (or considering using) `django-lti`? I appreciate the additional perspective.

**Comment by cmurtaugh** [comment]
@michaelwheeler yeah - we're about to start converting a number of our homegrown LTI 1.1 tools to 1.3 and are strongly considering using `django-lti`. I'd started to think about our own wrapper around `pylti1p3` but yours is more mature. Would love to talk about future directions at some point! My priorities are:

- ease the installation process / make it easy for LMS admins to manage integrations
- ease the development process - provide standardized views, easy access to LTI Advantage services
- ideally be able to handle multiple concurrent LTI sessions

**Comment by cmurtaugh** [comment]
BTW - I experimented with automatically creating deployments on demand here: 
https://github.com/academic-innovation/django-lti/commit/7f66e15e2f9729f5e861b996cec8f24f50cafba0

Very rough, but works. Would need to be configurable/customizable.

**Comment by michaelwheeler** [comment]
@cmurtaugh Working on an implementation for this at #60 if you are interested.

**Comment by michaelwheeler** [comment]
Closed by #60.
